[{"url":"https://api.github.com/repos/coq/coq/issues/comments/337521225","html_url":"https://github.com/coq/coq/issues/3445#issuecomment-337521225","issue_url":"https://api.github.com/repos/coq/coq/issues/3445","id":337521225,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUyMTIyNQ==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2014-07-21T09:39:27Z","updated_at":"2020-03-26T20:41:35Z","author_association":"CONTRIBUTOR","body":"Comment author: @JasonGross\r\n\r\n```coq\r\n(* File reduced by coq-bug-finder from original input, then from 7372 lines to 539 lines, then from 529 lines to 94 lines, then from 78 lines to 10 lines *)\r\nClass IsEquiv {A B : Type} (f : A -> B) := { equiv_inv : B -> A }.\r\nNotation \"f ^-1\" := (@ equiv_inv _ _ f _) (at level 3).\r\nDefinition path_sigma_hprop {A : Type} {P : A -> Type} (u v : sigT P) `{IsEquiv _ _ (@ projT1 A P)}\r\n  := projT1^-1.\r\n(* Toplevel input, characters 123-129:\r\nError:\r\nIn environment\r\nA : Type\r\nP : A -> Type\r\nu : {x : A & P x}\r\nv : {x : A & P x}\r\nH : IsEquiv (projT1 (P:=P))\r\nThe term \"projT1\" has type\r\n \"forall (A : Type) (P : A -> Type), {x : A & P x} -> A\"\r\nwhile it is expected to have type \"Type -> ?10\" (cannot instantiate\r\n\"?10\" because \"H\" is not in its scope: available arguments are\r\n\"H\" \"A\" \"P\" \"u\" \"v\").\r\n *)\r\n```","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337521225/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/337521226","html_url":"https://github.com/coq/coq/issues/3445#issuecomment-337521226","issue_url":"https://api.github.com/repos/coq/coq/issues/3445","id":337521226,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUyMTIyNg==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2015-06-19T07:02:04Z","updated_at":"2020-03-26T20:42:30Z","author_association":"CONTRIBUTOR","body":"Comment author: @silene\r\n\r\nAs far as I can tell, the reason is bogus only because of the lack of alpha-renaming. If you rename a few arguments manually, the message starts making sense:\r\n\r\n```coq\r\nRecord IsEquiv {A B : Type} (f : A -> B) := { equiv_inv : B -> A }.\r\nDefinition path_sigma_hprop {C : Type} {P : C -> Type} (u v : sigT P)\r\n  (K : IsEquiv (@ projT1 C P)) := equiv_inv projT1 _.\r\n(* cannot instantiate \"?B\" because \"A\" is not in its scope: available arguments are \"C\" \"P\" \"u\" \"v\" \"K\" *)\r\n```\r\n\r\nI let this bug open though, just in case someone knows of a simple way to ensure that the error message is displayed with fresh names for bound variables.\r\n\r\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337521226/reactions","total_count":1,"+1":1,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/798460195","html_url":"https://github.com/coq/coq/issues/3445#issuecomment-798460195","issue_url":"https://api.github.com/repos/coq/coq/issues/3445","id":798460195,"node_id":"MDEyOklzc3VlQ29tbWVudDc5ODQ2MDE5NQ==","user":{"login":"ejgallego","id":7192257,"node_id":"MDQ6VXNlcjcxOTIyNTc=","avatar_url":"https://avatars.githubusercontent.com/u/7192257?v=4","gravatar_id":"","url":"https://api.github.com/users/ejgallego","html_url":"https://github.com/ejgallego","followers_url":"https://api.github.com/users/ejgallego/followers","following_url":"https://api.github.com/users/ejgallego/following{/other_user}","gists_url":"https://api.github.com/users/ejgallego/gists{/gist_id}","starred_url":"https://api.github.com/users/ejgallego/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ejgallego/subscriptions","organizations_url":"https://api.github.com/users/ejgallego/orgs","repos_url":"https://api.github.com/users/ejgallego/repos","events_url":"https://api.github.com/users/ejgallego/events{/privacy}","received_events_url":"https://api.github.com/users/ejgallego/received_events","type":"User","site_admin":false},"created_at":"2021-03-13T14:41:04Z","updated_at":"2021-03-13T14:41:10Z","author_association":"MEMBER","body":"Renaming has changed but still seems to be a problem:\r\n```coq\r\nThe term \"projT1\" has type\r\n \"forall (A : Type) (P : A -> Type), {x : A & P x} -> A\"\r\nwhile it is expected to have type \"Type -> ?B\" (cannot instantiate \r\n\"?B\" because \"A0\" is not in its scope: available arguments are \r\n\"A\" \"P\" \"u\" \"v\" \"H\").\r\n```","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/798460195/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/798557791","html_url":"https://github.com/coq/coq/issues/3445#issuecomment-798557791","issue_url":"https://api.github.com/repos/coq/coq/issues/3445","id":798557791,"node_id":"MDEyOklzc3VlQ29tbWVudDc5ODU1Nzc5MQ==","user":{"login":"JasonGross","id":396076,"node_id":"MDQ6VXNlcjM5NjA3Ng==","avatar_url":"https://avatars.githubusercontent.com/u/396076?v=4","gravatar_id":"","url":"https://api.github.com/users/JasonGross","html_url":"https://github.com/JasonGross","followers_url":"https://api.github.com/users/JasonGross/followers","following_url":"https://api.github.com/users/JasonGross/following{/other_user}","gists_url":"https://api.github.com/users/JasonGross/gists{/gist_id}","starred_url":"https://api.github.com/users/JasonGross/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/JasonGross/subscriptions","organizations_url":"https://api.github.com/users/JasonGross/orgs","repos_url":"https://api.github.com/users/JasonGross/repos","events_url":"https://api.github.com/users/JasonGross/events{/privacy}","received_events_url":"https://api.github.com/users/JasonGross/received_events","type":"User","site_admin":false},"created_at":"2021-03-13T16:03:30Z","updated_at":"2021-03-13T16:03:30Z","author_association":"MEMBER","body":"Hm, I think this new error message is confusing because the renaming has been done in the wrong place.  I think there are two changes that should be made:\r\n1. the available arguments should be avoided as binder names in the type that is found\r\n2. and not-in-scope variables in the evar should ideally be shown as non-anonymous binders in the expected type\r\n\r\nNote, though, @ejgallego , that this example is supposed to error.  This bug report is merely about the ways in which the error message in this case are confusing.","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/798557791/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}]