[{"url":"https://api.github.com/repos/coq/coq/issues/comments/337536757","html_url":"https://github.com/coq/coq/issues/4363#issuecomment-337536757","issue_url":"https://api.github.com/repos/coq/coq/issues/4363","id":337536757,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUzNjc1Nw==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2015-10-07T23:50:31Z","updated_at":"2017-10-18T10:08:12Z","author_association":"CONTRIBUTOR","body":"Comment author: @JasonGross\n\nSet Printing Universes.\nDefinition foo : Type.\nProof.\n  assert (H : Set) by abstract (assert Type by abstract exact Type using bar; exact nat).\n  exact bar.\nDefined. (* Toplevel input, characters 0-8:\nError:\nThe term \"(fun _ : Set => bar) foo_subproof\" has type\n\"Type@ {Top.2}\" while it is expected to have type \"Type@ {Top.1}\". *)\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337536757/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/337536758","html_url":"https://github.com/coq/coq/issues/4363#issuecomment-337536758","issue_url":"https://api.github.com/repos/coq/coq/issues/4363","id":337536758,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUzNjc1OA==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2015-11-25T07:12:38Z","updated_at":"2017-10-18T10:08:13Z","author_association":"CONTRIBUTOR","body":"Comment author: @silene\n\nThe error is now\n\nAnomaly: Uncaught exception Not_found. Please report.\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337536758/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/337536760","html_url":"https://github.com/coq/coq/issues/4363#issuecomment-337536760","issue_url":"https://api.github.com/repos/coq/coq/issues/4363","id":337536760,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUzNjc2MA==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2015-11-26T12:34:04Z","updated_at":"2017-10-18T10:08:13Z","author_association":"CONTRIBUTOR","body":"Comment author: @silene\n\nActually, the anomaly is raised while looking for an identifier when fixing an exception (stm/lemmas.ml:211). So cc-ing Enrico, in case there is a simple way to improve the code so that failures during exception fixup cannot swallow the original error.\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337536760/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/337536764","html_url":"https://github.com/coq/coq/issues/4363#issuecomment-337536764","issue_url":"https://api.github.com/repos/coq/coq/issues/4363","id":337536764,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUzNjc2NA==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2015-11-26T17:29:42Z","updated_at":"2017-10-18T10:08:13Z","author_association":"CONTRIBUTOR","body":"Comment author: @gares\n\nNow the error is not masked.  It says:\n\nError:\nThe term \"(fun _ : Set => bar) foo_subproof\"\nhas type \"Type@ {Top.2}\"\nwhile it is expected to have type\n \"Type@ {Top.1}\".\n\nHope it helps.\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337536764/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/337536765","html_url":"https://github.com/coq/coq/issues/4363#issuecomment-337536765","issue_url":"https://api.github.com/repos/coq/coq/issues/4363","id":337536765,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUzNjc2NQ==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2015-12-11T16:57:17Z","updated_at":"2017-10-18T10:08:13Z","author_association":"CONTRIBUTOR","body":"Comment author: @mattam82\n\nFixed in 8.5, that was a bug in close_proof which was too eager removing universe constraints.\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337536765/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}]